version: '3.5'

# swarm-test-01

networks:
  apisix:
    external: true
  loki:
    external: true
  storage:
    external: true

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - /data/redis:/data:rw
    networks:
      - storage
    ports:
      - "6379:6379"
    restart: unless-stopped
    command:
      redis-server --requirepass yft
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-test-01
